autoInstallPeers: true
minimumReleaseAge: 4320

onlyBuiltDependencies:
- lefthook
                                                                                                         
strictPeerDependencies: false
